### PR TITLE
Accept rtc.io CLA

### PR DESCRIPTION
**Pull request by DamonOehlman**
I accept :)

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
How did that work for you? Feel ok?

**Comment by DamonOehlman** [comment]
Felt great.  I think if that tick's the legal boxes then that's fantastic and I don't think anyone would have a problem "signing" a CLA.

**Comment by silviapfeiffer** [comment]
OK we should socialise it on the mailing list, I guess.

**Comment by silviapfeiffer** [comment]
See https://groups.google.com/d/msg/rtc-io/nMbAudx8xGY/h6KnBQ_ioUAJ .

**Pull request merged**
